#!/bin/bash

checkinput = $(echo $1 | wc -c)

if [ '$checkinput' -lt '1' ]; then

  read -p "MGR login: " username
  read -p "MGR password: " password
  
  echo "Welcome $username!"
  exit
  
else
  
  echo "Welcome $1!"
  
fi

  
